spring.application.name=HomeCloudUI
spring.servlet.multipart.max-file-size=2GB
spring.servlet.multipart.max-request-size=2GB
server.address=0.0.0.0
server.port=8081
storage.url=http://localhost:8080

spring.datasource.url=jdbc:h2:file:~/My_files/h2db/homecloud_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
