spring.application.name=HomeCloudStorage

spring.servlet.multipart.max-file-size=2GB

spring.servlet.multipart.max-request-size=2GB

server.address=0.0.0.0
server.port=8080

#ngrok http 8080 --host-header=rewrite
